# 将静态内容部署到 GitHub Pages 的简单工作流程
name :名称：将静态内容部署到页面

在：
  #针对默认分支的本体上运动#针对默认分支的本体上运动
  推：推：
    分支：[ “主要” ]

  # 允许您从“操作”选项卡手动运行此工作流程# 允许您从“操作”选项卡手动运行此工作流程
  工作流程_调度：

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
权限：
  内容： 内容： 阅读
  页码： 页码：写
  id-token  :     id 令牌：写入

# 仅允许一个队列运行，跳过队列的运行和最新队列的运行之间的队列运行。
#但是，不要取消发射的运行，因为我们希望完成这些生产部署。
系数：
  组：“页面”
  取消进行中：false

职位：
  # 单个部署作业，因为我们刚刚部署
  部署：
    环境：
      名称：github-pages
网址：$ { { steps.deployment.outputs.page_url } } { { steps.deployment.outputs.page_url } }
    running-on :     运行：ubuntu-latest
    步骤：
      -名称:        - 名称：结账
        使用：         使用：actions/checkout@v4
      - name :        - 名称：设置页面
        使用：         使用：actions/configure-pages@v5
      -姓名 :        - 名称：上传神器
        用途：actions/upload-pages-artifact@v3
        和：
          # 上传整个存储库
          小路：'。'
      -姓名：部署到 GitHub 页面
        编号： 部署
        使用：actions/deploy-pages@v4
